UPDATE Jenkinsfile for parallel stage execution
CentOS-PaaS-SIG/ci-pipeline pull request #455
Opened 2017-10-24 14:27 UTC by robnester-rh

Updated the Jenkinsfile and associated library files to allow testing
stages to run in parallel.

2017-10-24 14:32 UTC, johnbieren requested changes

2017-10-24 14:32 UTC, johnbieren commented on Jenkinsfile
> +                    }, functionalj-tests {
typo

2017-10-24 14:32 UTC, johnbieren commented on Jenkinsfile
> +                                messageFields = pipelineUtils.setMessageFields("package.test.functional.queued")
Gotta move all the .queued messages to right before parallel step

2017-10-24 14:54 UTC, johnbieren approved these changes
lgtm

2017-10-24 15:11 UTC, scoheb commented
Lgtm

2017-10-27 17:53 UTC, robnester-rh commented
[test]

2017-10-27 23:56 UTC, robnester-rh commented
[test]

2017-11-13 21:20 UTC, robnester-rh commented
Just a note, this latest push is meant for testing purposes; no need to review code at the moment.

2017-11-16 16:08 UTC, scoheb commented on Jenkinsfile
> -                        image: DOCKER_REPO_URL + '/' + OPENSHIFT_NAMESPACE + '/jenkins-continuous-infra-slave:' + SLAVE_TAG,
you do not like my distinct touch here? ;)

2017-11-16 16:08 UTC, scoheb approved these changes

2017-11-29 14:28 UTC, robnester-rh commented
[test]

2017-11-29 17:55 UTC, robnester-rh commented
[test]

2017-11-29 18:19 UTC, robnester-rh commented
[test]

2017-11-30 16:53 UTC, robnester-rh commented
[test]

2017-11-30 18:39 UTC, robnester-rh commented
[test]

2017-11-30 19:12 UTC, robnester-rh commented
[test]

2017-12-01 14:16 UTC, robnester-rh commented
[test]

2017-12-01 15:01 UTC, robnester-rh commented
[test]

2023-09-25 19:55 UTC, closed without merging